// <auto-generated />
using System;
using System.Collections.Generic;
using AmazonApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElAhorrador.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230708081757_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AmazonApi.Models.AmazonProduct", b =>
                {
                    b.Property<string>("Asin")
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasStock")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InitialScrapedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastScrapedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("numeric");

                    b.Property<List<decimal>>("PreviousPrices")
                        .HasColumnType("numeric[]");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Stars")
                        .HasColumnType("numeric");

                    b.HasKey("Asin");

                    b.ToTable("AmazonProducts");
                });

            modelBuilder.Entity("ElAhorrador.Models.Configuration", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
